name: "GitHub Presente Brasil"
description: "Event to invite community speakers for GitHub Presente"
labels:
  - "event"
  - "meetup"
assignees: [pachicodes]
---

## Event Details

- **Host:** [HOST_NAME]
- **Date and Time:** [DATE TIME]
- **Location:** [LOCATION]

### Speakers
Please list the speakers and their talks.

- **Speaker 1:** Talk 1
- **Speaker 2:** Talk 2

### Agenda
Outline the structure of the event:

- Quick intros
- Talks
- Q&A
- Networking session

### To-do List
#### Before the Event

- [ ] Send invitations
- [ ] Create graphic assets
- [ ] Create event on Meetup
- [ ] Create Streamyard and LinkedIn live events
- [ ] Prepare slide deck
- [ ] Share details with Social Media team

#### After the Event

- [ ] Share talk links with Speakers
- [ ] Post event content on social media
- [ ] Highlight talks on Twitch
