## GitHub Presente, DATE TIME
Host: "[HOST_NAME]"

Speakers_and_talks:
  - Speaker 1: "Talk 1"
  - Speaker 2: "Talk 2"

### Program Structure:
- Quick intros
- Talks
- Q&A
- Networking session

### To-do:
Before:
  - [ ] Send invitations
  - [ ] Create graphic assets
  - [ ] Create event on Meetup
  - [ ] Create Streamyard and LinkedIn live events
  - [ ] Prepare slide deck
  - [ ] Share details with Social Media team

After:
  - [ ] Highlight talks on Twitch
  - [ ] Share talk links with Speakers
  - [ ] Post event content on social media
