## GitHub Presente BR, DATE TIME
Host: 

Speakers and talks: 


### Program Structure:
- Quick intros
- Talks
- Q&A
- Networking session


### To-do:
## Before
- [] Sent invitations
- [] Create graphic assets
- [] Create event on Meetup 
- [] Create Streamyard and LinkedIn live events
- [] Slide deck
- [] Share with Social

## After
- [] Highlight talks on Twitch
- [] Share talk links with Speakers
- [] Share on social
